### ISSUE TITLE
Some locks still persist after week is over

### ISSUE THREAD

**Issue by riddle** [CoreNetwork/Challenges#21]
Overworld:

``` yaml
w22t2-jonthehobo123:
        type: cuboid
        min: {x: -1852.0, y: 13.0, z: -1863.0}
        max: {x: -1849.0, y: 14.0, z: -1861.0}
        priority: 0
        flags: {pistons: deny, chest-access: deny, build: deny}
        owners: {}
        members: {}
```

Nether:

``` yaml
regions:
    w22t2-onsens:
        type: cuboid
        min: {x: -422.0, y: 30.0, z: 271.0}
        max: {x: -419.0, y: 31.0, z: 273.0}
        priority: 0
        flags: {pistons: deny, chest-access: deny, build: deny}
        owners: {}
        members: {}
    w22t2-risenashes:
        type: cuboid
        min: {x: 291.0, y: 77.0, z: 99.0}
        max: {x: 293.0, y: 78.0, z: 101.0}
        priority: 0
        flags: {pistons: deny, chest-access: deny, build: deny}
        owners: {}
        members: {}
    w22t2-sinocopa5:
        type: cuboid
        min: {x: 152.0, y: 31.0, z: 551.0}
        max: {x: 154.0, y: 32.0, z: 553.0}
        priority: 0
        flags: {pistons: deny, chest-access: deny, build: deny}
        owners: {}
        members: {}
    w22t4-theor:
        type: cuboid
        min: {x: -628.0, y: 42.0, z: -235.0}
        max: {x: -600.0, y: 55.0, z: -214.0}
        priority: 0
        flags: {pistons: deny, chest-access: deny, build: deny}
        owners: {}
        members: {}
```

There were many more locks, but these were left out. You can see they’re not manual as they have flags while we never add flags manually.
