### ISSUE TITLE
Exploding an entry and approving levels independently shows double rankup messages

### ISSUE THREAD

**Issue by riddle** [CoreNetwork/Challenges#30]
http://imgur.com/a/T8m1B

I had to explode his entry (levels 3 and 4), approved 3rd, the message displayed, then i teleported to 4th, approved it and the same message about the rankup displayed.

Moreover, /chm points ijzervarken shows he has 74 points and we need 75 to get that:

``` yaml
  Veteran Raider:
    PointsNeeded: 75
    PEXGroup: Raider
    Suffix: ++
```

Upon further inspection in GroupManager

``` yaml
  ijzervarken:
    group: Raider
    subgroups: []
    permissions: []
    info:
      suffix: +
```

He indeed needs one more point. Which means messages were false (and doubled… double bug?)
