### ISSUE TITLE
Old lock issue

### ISSUE THREAD

**Issue by riddle** [CoreNetwork/Challenges#37]
``` yaml
    w45t4-deh59:
        type: cuboid
        min: {x: -498.0, y: 63.0, z: 141.0}
        max: {x: -479.0, y: 73.0, z: 160.0}
        priority: 0
        flags: {pistons: deny, chest-access: deny, build: deny}
        owners: {}
        members: {}
```

This was still in the file and current’s week prefix is `w46`.
