### ISSUE TITLE
Move out variables to 2nd config file

### ISSUE THREAD

**Issue by riddle** [CoreNetwork/Challenges#64]
``` yaml
CurrentWeekStart: 1394992800
CurrentWeek: 63
Stopped: false
```

This poses a problem if the file is being edited before new challenge week arrives and saved, overwriting `CurrentWeek` and causing problems.

This data should be exported to `storage.yml` or something.
