### ISSUE TITLE
Add more flags to locked areas

### ISSUE THREAD

**Issue by riddle** [CoreNetwork/Challenges#74]
``` yaml
creeper-explosion: deny
ghast-fireball: deny
enderman-grief: deny
entity-item-frame-destroy: deny
entity-painting-destroy: deny
```
